# Generated by Django 4.2.1 on 2023-08-17 15:54

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': (('change_avatar', 'can change avatar of profile'),)},
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to=accounts.models.profile_avatar_directory_path, verbose_name='Avatar'),
        ),
    ]
