# Generated by Django 4.2.1 on 2023-06-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_order_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price']},
        ),
    ]
